### ISSUE TITLE
사이트 접속 시 사이트가 정상적으로 표시되지 않습니다.

### ISSUE THREAD

**Issue by Kwak04** [5d-jh/neis_code_finder#2]
<img width="1871" alt="스크린샷 2019-09-02 오후 10 05 38" src="https://user-images.githubusercontent.com/48079406/64116665-eb3acd80-cdcd-11e9-9237-c86744c6647f.png">

사이트 접속 시 화면입니다.
감사합니다.

**Comment by 5d-jh** [comment]
일단 새 임시 서버를 오픈했습니다. 다음 링크로 들어와주세요
https://neiscodefinder.azurewebsites.net

**Comment by 5d-jh** [comment]
클라우드 서비스 변경 과정에서 URL을 변경하게 됐습니다. 이제 [여기](https://schoolcodekr.ml)로 들어와주세요. 감사합니다.
