### ISSUE TITLE
사이트 접속 후 학교 검색을 하면 504 Gateway Time-out 오류가 발생합니다.

### ISSUE THREAD

**Issue by gguggu** [5d-jh/neis_code_finder#3]
![neis504오류](https://user-images.githubusercontent.com/48512207/66894779-3d594a80-f02c-11e9-87a7-197dcc8c9b61.png)

[https://schoolcodekr.ml/](url)  링크에 접속 후 학교를 검색하면 위와 같이 504가 발생합니다.

**Comment by 5d-jh** [comment]
클라우드에 문제가 생겨서 서버가 완전히 닫힌 상태입니다. 지금으로선 [소스코드](https://github.com/5d-jh/neis_code_finder/blob/master/app/get_code.py)를 참고해서 학교알리미 사이트로 직접 불러오는 방법밖에 없겠네요.. 불편을 드려 죄송합니다.

**Comment by gguggu** [comment]
아 그렇군요. 답변 감사합니다.

**Comment by 5d-jh** [comment]
해결이 늦어서 죄송합니다. 클라우드 문제를 해결하여 서버를 다시 열었습니다. 이제 이 링크로 들어와주세요: https://www.schoolcodekr.ml/app
